export const types = {
  UPDATE_STATE: "UPDATE_STATE",
  UPDATE_FORM_DATA: "UPDATE_FORM_DATA",
  POST_DATA_LOADNING: "POST_DATA_LOADNING",
  POST_DATA_SUCCESS: "POST_DATA_SUCCESS",
  POST_DATA_ERROR: "POST_DATA_ERROR",
  CLEAR_STATE: "CLEAR_STATE",
};
